project:
  type: website
  render: 
    - index.qmd
    - homicide.qmd
    - un-info-API-R.qmd

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: homicide.qmd
        text: Homicide
      - href: un-info-API-R.qmd
        text: UN INFO API


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto