project:
  type: website
  render: 
    - index.qmd
    - analysis.qmd
    - un-info-API-R.qmd

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      - href: un-info-API-R.qmd
        text: UN INFO API

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto